# Generated by Django 6.0.6 on 2026-06-25 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("single", "Single"), ("couple", "Couple")],
                        max_length=20,
                    ),
                ),
                ("places", models.PositiveIntegerField(default=1)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "table_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("qr_payload", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="generated", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
