# Generated by Django 6.0.6 on 2026-06-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="qr_payload",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="status",
        ),
        migrations.AddField(
            model_name="guest",
            name="is_checked_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="guest",
            name="qr_code",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="table_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
