# Generated by Django 6.0.6 on 2026-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0002_remove_guest_qr_payload_remove_guest_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="qr_code",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="guest",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="ticket_type",
            field=models.CharField(
                choices=[("single", "Single"), ("couple", "Couple")],
                default="single",
                max_length=20,
            ),
        ),
    ]
