# Generated by Django 6.0.6 on 2026-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0003_alter_guest_qr_code_alter_guest_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={
                "ordering": ["display_name"],
                "verbose_name": "Invité",
                "verbose_name_plural": "Invités",
            },
        ),
        migrations.AddField(
            model_name="guest",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="invitation_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="display_name",
            field=models.CharField(max_length=255, verbose_name="Nom affiché"),
        ),
        migrations.AlterField(
            model_name="guest",
            name="qr_code",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
